[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  WC_KEY = "sua-chave-woocommerce"
  WC_SECRET = "sua-senha-woocommerce"
  WOOCOMMERCE_API_BASE = "https://sualoja.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
